In [10]:
#Python Warning off
import warnings
warnings.filterwarnings('ignore')

# #TF warning off
# import tensorflow as tf
# tf.compat.v2.logging.set_verbosity(tf.compat.v2.logging.ERROR)

In [11]:
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd

In [22]:
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense
from keras.utils import np_utils

ModuleNotFoundError: No module named 'keras'

In [12]:
import tensorflow as tf

In [13]:
from tensorflow import keras

In [14]:
#RandomForest

In [15]:
df_raw = pd.read_csv("datasets/hotel_bookings.csv")
df_raw

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.00,0,1,Check-Out,2015-07-03
5,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.00,0,1,Check-Out,2015-07-03
6,Resort Hotel,0,0,2015,July,27,1,0,2,2,...,No Deposit,NaN,NaN,0,Transient,107.00,0,0,Check-Out,2015-07-03
7,Resort Hotel,0,9,2015,July,27,1,0,2,2,...,No Deposit,303.0,NaN,0,Transient,103.00,0,1,Check-Out,2015-07-03
8,Resort Hotel,1,85,2015,July,27,1,0,3,2,...,No Deposit,240.0,NaN,0,Transient,82.00,0,1,Canceled,2015-05-06
9,Resort Hotel,1,75,2015,July,27,1,0,3,2,...,No Deposit,15.0,NaN,0,Transient,105.50,0,0,Canceled,2015-04-22
10,Resort Hotel,1,23,2015,July,27,1,0,4,2,...,No Deposit,240.0,NaN,0,Transient,123.00,0,0,Canceled,2015-06-23
11,Resort Hotel,0,35,2015,July,27,1,0,4,2,...,No Deposit,240.0,NaN,0,Transient,145.00,0,0,Check-Out,2015-07-05
12,Resort Hotel,0,68,2015,July,27,1,0,4,2,...,No Deposit,240.0,NaN,0,Transient,97.00,0,3,Check-Out,2015-07-05
13,Resort Hotel,0,18,2015,July,27,1,0,4,2,...,No Deposit,241.0,NaN,0,Transient,154.77,0,1,Check-Out,2015-07-05
14,Resort Hotel,0,37,2015,July,27,1,0,4,2,...,No Deposit,241.0,NaN,0,Transient,94.71,0,0,Check-Out,2015-07-05
15,Resort Hotel,0,68,2015,July,27,1,0,4,2,...,No Deposit,240.0,NaN,0,Transient,97.00,0,3,Check-Out,2015-07-05
16,Resort Hotel,0,37,2015,July,27,1,0,4,2,...,No Deposit,8.0,NaN,0,Contract,97.50,0,0,Check-Out,2015-07-05
17,Resort Hotel,0,12,2015,July,27,1,0,1,2,...,No Deposit,240.0,NaN,0,Transient,88.20,0,0,Check-Out,2015-07-02
18,Resort Hotel,0,0,2015,July,27,1,0,1,2,...,No Deposit,NaN,110.0,0,Transient,107.42,0,0,Check-Out,2015-07-02
19,Resort Hotel,0,7,2015,July,27,1,0,4,2,...,No Deposit,250.0,NaN,0,Transient,153.00,0,1,Check-Out,2015-07-05
20,Resort Hotel,0,37,2015,July,27,1,1,4,1,...,No Deposit,241.0,NaN,0,Transient,97.29,0,1,Check-Out,2015-07-06
21,Resort Hotel,0,72,2015,July,27,1,2,4,2,...,No Deposit,250.0,NaN,0,Transient,84.67,0,1,Check-Out,2015-07-07
22,Resort Hotel,0,72,2015,July,27,1,2,4,2,...,No Deposit,250.0,NaN,0,Transient,84.67,0,1,Check-Out,2015-07-07
23,Resort Hotel,0,72,2015,July,27,1,2,4,2,...,No Deposit,250.0,NaN,0,Transient,99.67,0,1,Check-Out,2015-07-07
24,Resort Hotel,0,127,2015,July,27,1,2,5,2,...,No Deposit,115.0,NaN,0,Contract,94.95,0,1,Check-Out,2015-07-01
25,Resort Hotel,0,78,2015,July,27,1,2,5,2,...,No Deposit,5.0,NaN,0,Transient,63.60,1,0,Check-Out,2015-07-08
26,Resort Hotel,0,48,2015,July,27,1,2,5,2,...,No Deposit,8.0,NaN,0,Contract,79.50,0,0,Check-Out,2015-07-08
27,Resort Hotel,1,60,2015,July,27,1,2,5,2,...,No Deposit,240.0,NaN,0,Transient,107.00,0,2,Canceled,2015-05-11
28,Resort Hotel,0,77,2015,July,27,1,2,5,2,...,No Deposit,240.0,NaN,0,Transient,94.00,0,0,Check-Out,2015-07-08
29,Resort Hotel,0,99,2015,July,27,1,2,5,2,...,No Deposit,240.0,NaN,0,Transient,87.30,1,1,Check-Out,2015-07-08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119360,City Hotel,0,195,2017,August,35,29,1,5,2,...,No Deposit,9.0,NaN,0,Transient,117.00,0,1,Check-Out,2017-09-04
119361,City Hotel,0,100,2017,August,35,31,1,3,2,...,No Deposit,16.0,NaN,0,Transient,95.85,0,0,Check-Out,2017-09-04
119362,City Hotel,0,198,2017,August,35,29,1,5,2,...,No Deposit,9.0,NaN,0,Transient,119.17,0,2,Check-Out,2017-09-04
119363,City Hotel,0,212,2017,August,35,28,2,5,2,...,No Deposit,7.0,NaN,0,Transient,92.17,0,1,Check-Out,2017-09-04
119364,City Hotel,0,212,2017,August,35,28,2,5,2,...,No Deposit,7.0,NaN,0,Transient,92.17,0,2,Check-Out,2017-09-04
119365,City Hotel,0,54,2017,August,35,27,3,5,1,...,No Deposit,14.0,NaN,0,Transient,266.75,0,1,Check-Out,2017-09-04
119366,City Hotel,0,210,2017,August,35,28,2,5,2,...,No Deposit,7.0,NaN,0,Transient,85.59,0,1,Check-Out,2017-09-04
119367,City Hotel,0,212,2017,August,35,28,2,5,2,...,No Deposit,7.0,NaN,0,Transient,85.59,0,0,Check-Out,2017-09-04
119368,City Hotel,0,261,2017,August,35,30,1,4,2,...,No Deposit,14.0,NaN,0,Transient,99.00,0,0,Check-Out,2017-09-04
119369,City Hotel,0,207,2017,August,34,25,3,7,2,...,No Deposit,14.0,NaN,0,Transient,96.25,0,2,Check-Out,2017-09-04
119370,City Hotel,0,201,2017,August,35,30,1,4,1,...,No Deposit,9.0,NaN,0,Transient,108.00,0,2,Check-Out,2017-09-04
119371,City Hotel,0,175,2017,August,35,31,1,3,2,...,No Deposit,42.0,NaN,0,Transient,86.85,0,2,Check-Out,2017-09-04
119372,City Hotel,0,175,2017,August,35,31,1,3,1,...,No Deposit,42.0,NaN,0,Transient,82.35,0,1,Check-Out,2017-09-04
119373,City Hotel,0,175,2017,August,35,31,1,3,1,...,No Deposit,42.0,NaN,0,Transient,82.35,0,1,Check-Out,2017-09-04
119374,City Hotel,0,201,2017,August,35,29,1,5,2,...,No Deposit,9.0,NaN,0,Transient,117.00,0,2,Check-Out,2017-09-04
119375,City Hotel,0,200,2017,August,35,30,1,4,2,...,No Deposit,16.0,NaN,0,Transient,85.50,0,1,Check-Out,2017-09-04
119376,City Hotel,0,165,2017,August,35,29,1,5,3,...,No Deposit,9.0,NaN,0,Transient,209.25,0,3,Check-Out,2017-09-04
119377,City Hotel,0,185,2017,August,35,30,1,4,2,...,No Deposit,9.0,NaN,0,Transient,99.00,0,1,Check-Out,2017-09-04
119378,City Hotel,0,247,2017,August,35,31,1,3,2,...,No Deposit,42.0,NaN,0,Transient,86.85,0,0,Check-Out,2017-09-04
119379,City Hotel,0,109,2017,August,35,31,1,3,2,...,No Deposit,9.0,NaN,0,Transient,155.00,0,1,Check-Out,2017-09-04
119380,City Hotel,0,44,2017,August,35,31,1,3,2,...,No Deposit,9.0,NaN,0,Transient,140.75,0,1,Check-Out,2017-09-04
119381,City Hotel,0,188,2017,August,35,31,2,3,2,...,No Deposit,14.0,NaN,0,Transient,99.00,0,0,Check-Out,2017-09-05
119382,City Hotel,0,135,2017,August,35,30,2,4,3,...,No Deposit,7.0,NaN,0,Transient,209.00,0,0,Check-Out,2017-09-05
119383,City Hotel,0,164,2017,August,35,31,2,4,2,...,No Deposit,42.0,NaN,0,Transient,87.60,0,0,Check-Out,2017-09-06
119384,City Hotel,0,21,2017,August,35,30,2,5,2,...,No Deposit,394.0,NaN,0,Transient,96.14,0,2,Check-Out,2017-09-06
119385,City Hotel,0,23,2017,August,35,30,2,5,2,...,No Deposit,394.0,NaN,0,Transient,96.14,0,0,Check-Out,2017-09-06
119386,City Hotel,0,102,2017,August,35,31,2,5,3,...,No Deposit,9.0,NaN,0,Transient,225.43,0,2,Check-Out,2017-09-07
119387,City Hotel,0,34,2017,August,35,31,2,5,2,...,No Deposit,9.0,NaN,0,Transient,157.71,0,4,Check-Out,2017-09-07
119388,City Hotel,0,109,2017,August,35,31,2,5,2,...,No Deposit,89.0,NaN,0,Transient,104.40,0,0,Check-Out,2017-09-07
119389,City Hotel,0,205,2017,August,35,29,2,7,2,...,No Deposit,9.0,NaN,0,Transient,151.20,0,2,Check-Out,2017-09-07

In [16]:
df_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
hotel                             119390 non-null object
is_canceled                       119390 non-null int64
lead_time                         119390 non-null int64
arrival_date_year                 119390 non-null int64
arrival_date_month                119390 non-null object
arrival_date_week_number          119390 non-null int64
arrival_date_day_of_month         119390 non-null int64
stays_in_weekend_nights           119390 non-null int64
stays_in_week_nights              119390 non-null int64
adults                            119390 non-null int64
children                          119386 non-null float64
babies                            119390 non-null int64
meal                              119390 non-null object
country                           118902 non-null object
market_segment                    119390 non-null object
distribution_channel              119390 non-null object
is_repeated_guest                 119390 non-null int64
previous_cancellations            119390 non-null int64
previous_bookings_not_canceled    119390 non-null int64
reserved_room_type                119390 non-null object
assigned_room_type                119390 non-null object
booking_changes                   119390 non-null int64
deposit_type                      119390 non-null object
agent                             103050 non-null float64
company                           6797 non-null float64
days_in_waiting_list              119390 non-null int64
customer_type                     119390 non-null object
adr                               119390 non-null float64
required_car_parking_spaces       119390 non-null int64
total_of_special_requests         119390 non-null int64
reservation_status                119390 non-null object
reservation_status_date           119390 non-null object
dtypes: float64(4), int64(16), object(12)
memory usage: 29.1+ MB

In [17]:
df = df.apply(pd.to_numeric, errors='coerce')

In [19]:
cols = ['hotel', 'lead_time','arrival_date_month','previous_cancellations','previous_bookings_not_canceled','booking_changes','adr']

In [20]:
y = df['is_canceled']

In [21]:
y =  np_utils.to_categorical(y)
y

NameError: name 'np_utils' is not defined